# Generated by Django 4.2.7 on 2023-11-21 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Car',
        ),
    ]
