# Generated by Django 4.2.7 on 2023-11-24 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_subject_studentmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_name']},
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='subject_name',
        ),
    ]
