# Generated by Django 4.2.7 on 2023-11-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentMarks',
            new_name='SubjectMarks',
        ),
    ]
